### ISSUE TITLE
Error in callback for watcher "text": "Error: code length overflow. (1756>1056)

### ISSUE THREAD

**Issue by salman652** [gerardreches/vue-qrcode-component#15]
vue.common.dev.js:1932 Error: code length overflow. (1756>1056)
    at ./node_modules/qrcode-js-package/qrcode.js.QRCodeModel.createData (qrcode.js:340:1)
    at QRCodeModel.makeImpl (qrcode.js:129:1)
    at QRCodeModel.getBestMaskPattern (qrcode.js:154:1)
    at QRCodeModel.make (qrcode.js:103:1)
    at ./node_modules/qrcode-js-package/qrcode.js.QRCode.makeCode (qrcode.js:1302:1)
    at VueComponent.makeCode (QRCode.vue?53dc:63:1)
    at VueComponent.text (QRCode.vue?53dc:40:1)
    at Watcher.run (vue.common.dev.js:4554:1)
    at flushSchedulerQueue (vue.common.dev.js:4290:1)
    at Array.<anonymous> (vue.common.dev.js:2028:1)

**Comment by gerardreches** [comment]
Can't reproduce
